homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 37
  unit_system: imperial
  time_zone: America/New_York
  auth_providers:
    - type: homeassistant

frontend:
http:
  ip_ban_enabled: True
  login_attempts_threshold: 10
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.3
discovery:
conversation:
history:
logbook:
map:
sun:
config:
system_health:
stream:

wemo:

mqtt:
  broker: mosquitto
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

aqualogic:
  host: 192.168.68.127
  port: 8899

panel_iframe:
  nodered:
    title: NodeRed
    icon: mdi:shuffle-variant
    url: http://skywalker.local:1880
    require_admin: true
  grafana:
    title: Grafana
    icon: mdi:wrench
    url: http://skywalker.local:3000
    require_admin: true

sensor:
  - platform: aqualogic
    monitored_conditions:
      - pool_temp
      - spa_temp
      - status

switch:
  - platform: aqualogic
    monitored_conditions:
      - filter
      - lights
      - aux_1
device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.68.69
      - 192.168.68.68
      - 192.168.68.67
      - 192.168.68.58
      - 192.168.68.50
      - 192.168.68.54
    home_interval: 5

cover:
  - platform: garadget
    covers:
      47004d001151353432393433:
        access_token: !secret garadget_token
        name: Garage Door

amcrest:
  - host: 192.168.68.122
    name: Garage
    username: admin
    password: !secret armcrest_password
    resolution: high
    stream_source: rtsp
    binary_sensors:
      - motion_detected
  - host: 192.168.68.108
    name: Playroom
    username: admin
    password: !secret armcrest_password
    resolution: high
    stream_source: rtsp
    binary_sensors:
      - motion_detected

recorder:
  db_url: !secret db_url
  exclude:
    domains:
      - automation
      - updater
      - input_boolean
      - input_number
      - input_select
      - input_datetime
      - input_string
      - script
    entities:
      - group.machine_info
      - sun.sun
      - sensor.date
  include:
    domains:
      - binary_sensor
      - cover
      - device_tracker
      - light
      - sensor
      - switch
      - media_player
      - person

automation:
  - alias: Front Lights On
    trigger:
      platform: sun
      event: sunset
    action:
      service: switch.turn_on
      entity_id: switch.front_porch_overhead_light
  - alias: Front Lights Off
    trigger:
      platform: sun
      event: sunrise
    action:
      service: switch.turn_off
      entity_id: switch.front_porch_overhead_light
