homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 37
  unit_system: imperial
  time_zone: America/New_York
  auth_providers:
    - type: homeassistant
  customize: !include customize.yaml
  country: US

frontend:
http:
  # ip_ban_enabled: True
  # login_attempts_threshold: 50
  use_x_forwarded_for: true
  trusted_proxies:
    # - 192.168.68.0/20  # Local Lan
    - 172.18.0.0/16  # Docker net
    - 127.0.0.1
conversation:
history:
logbook:
map:
sun:
config:
system_health:
stream:
default_config:

wemo:

input_number:
  slider:
    name: Sprinkler Duration
    initial: 5 # in minutes
    min: 1
    max: 30
    step: 1

mqtt:
  cover:
    - name: "Garage Door"
      command_topic: "garadget/Garage/command"
      state_topic: "garadget/Garage/status"
      payload_open: "open"
      payload_close: "close"
      state_open: "open"
      state_closed: "closed"
      value_template: '{{ value_json.status }}'

aqualogic:
  host: !secret aqualogic_host
  port: 8899

panel_iframe:
  nodered:
    title: NodeRed
    icon: mdi:shuffle-variant
    url: http://skywalker.local:1880/nodered-iframe
    require_admin: true

sensor:
  - platform: sql
    db_url: !secret peripheral_url
    queries:
      - name: Rain Last Hour
        query: "select sum(amount_since_last_read) as rainfall from rain_sensor where read_at > (select now() - interval '1' hour);"
        column: "rainfall"
        unit_of_measurement: mm
      - name: Rain Last Day
        query: "select sum(amount_since_last_read) as rainfall from rain_sensor where read_at > (select now() - interval '24' hour);"
        column: "rainfall"
        unit_of_measurement: mm
      - name: Rain Last Week
        query: "select sum(amount_since_last_read) as rainfall from rain_sensor where read_at > (select now() - interval '168' hour);"
        column: "rainfall"
        unit_of_measurement: mm
  - platform: aqualogic
    monitored_conditions:
      - pool_temp
      - spa_temp
      - status
 
switch:
  - platform: aqualogic
    monitored_conditions:
      - filter
      - lights
      - aux_1

telegram_bot:
  platform: polling
  api_key: !secret telegram_key
  allowed_chat_ids:
    - !secret telegram_chat_id

notify:
 - name: halladay_bot
   platform: telegram
   chat_id: !secret telegram_chat_id

amcrest:
  - host: !secret garage_camera_host
    name: Garage
    username: admin
    password: !secret armcrest_password
    resolution: high
    stream_source: rtsp
    binary_sensors:
      - motion_detected
  - host: !secret playroom_camera_host
    name: Playroom
    username: admin
    password: !secret armcrest_password
    resolution: high
    stream_source: rtsp
    binary_sensors:
      - motion_detected

recorder:
  db_url: !secret db_url
  exclude:
    domains:
      - automation
      - updater
      - input_boolean
      - input_number
      - input_select
      - input_datetime
      - input_string
      - script
    entities:
      - group.machine_info
      - sun.sun
      - sensor.date
  include:
    domains:
      - binary_sensor
      - cover
      - device_tracker
      - light
      - sensor
      - switch
      - media_player
      - person
device_tracker:
  - platform: iphonedetect
    consider_home: 60
    new_device_defaults:
      track_new_devices: true
    hosts:
      sarah_iphone: !secret sarah_iphone_host
      amanda_iphone: !secret amanda_iphone_host
      noah_iphone: !secret noah_iphone_host
      brianna_iphone: !secret brianna_iphone_host
      samantha_iphone: !secret samantha_iphone_host

group:
  family:
    name: Family
    entities:
      - person.david
      - person.sarah
      - person.amanda
      - person.noah
      - person.brianna
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
      - room_numbers
      - rooms
    auto_update: false
automation: !include automations.yaml

o365:
  accounts:
    - account_name: !secret o365_account_name
      client_id: !secret o365_client_id
      client_secret: !secret o365_client_secret
      alt_auth_method: False
      enable_update: True

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    code_arm_required: false # Don't need code to arm.
    disarm_after_trigger: false # Leave alarm armed after triggering.
    arming_time: 60 # Time to leave the house after arming.
    delay_time: 60 # Time to turn off after entering the house.
    trigger_time: 600 # How long the alarm goes off for.
    disarmed:
      trigger_time: 0 # Can't be triggered when disarmed.
    armed_home:
      arming_time: 0 # Arm instantly when at home.
      delay_time: 0 # Trigger instantly when at home.
