homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 350
  unit_system: us_customary
  time_zone: America/Los_Angeles
  auth_providers:
    - type: homeassistant
  customize: !include customize.yaml
  country: US

frontend:
http:
  # ip_ban_enabled: True
  # login_attempts_threshold: 50
  use_x_forwarded_for: true
  trusted_proxies:
    # - 192.168.68.0/20  # Local Lan
    - 172.18.0.0/16  # Docker net
    - 127.0.0.1
conversation:
history:
logbook:
map:
sun:
config:
system_health:
stream:
default_config:

wemo:

mqtt:
  cover:
    - name: "Garage Door"
      command_topic: "garadget/Garage/command"
      state_topic: "garadget/Garage/status"
      payload_open: "open"
      payload_close: "close"
      state_open: "open"
      state_closed: "closed"
      value_template: '{{ value_json.status }}'


notify:
 - name: halladay_bot
   platform: telegram
   chat_id: !secret telegram_chat_id

amcrest:
  - host: !secret garage_camera_host
    name: Garage
    username: admin
    password: !secret armcrest_password
    resolution: high
    stream_source: rtsp
    binary_sensors:
      - motion_detected
  - host: !secret playroom_camera_host
    name: Playroom
    username: admin
    password: !secret armcrest_password
    resolution: high
    stream_source: rtsp
    binary_sensors:
      - motion_detected

recorder:
  db_url: !secret db_url
  exclude:
    domains:
      - automation
      - updater
      - input_boolean
      - input_number
      - input_select
      - input_datetime
      - input_string
      - script
    entities:
      - group.machine_info
      - sun.sun
      - sensor.date
  include:
    domains:
      - binary_sensor
      - cover
      - device_tracker
      - light
      - sensor
      - switch
      - media_player
      - person

group:
  family:
    name: Family
    entities:
      - person.david
      - person.sarah
      - person.noah
      - person.brianna
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
      - rooms
    auto_update: false
automation: !include automations.yaml
