homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 37
  unit_system: imperial
  time_zone: America/New_York
  auth_providers:
    - type: homeassistant
  customize: !include customize.yaml

frontend:
http:
  # ip_ban_enabled: True
  # login_attempts_threshold: 50
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.0/24
    - 127.0.0.1
discovery:
conversation:
history:
logbook:
map:
sun:
config:
system_health:
stream:
default_config:

wemo:

mqtt:
  broker: mosquitto
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

aqualogic:
  host: 192.168.68.69
  port: 8899

panel_iframe:
  nodered:
    title: NodeRed
    icon: mdi:shuffle-variant
    url: https://home.davidhalladay.com/nodered-iframe
    require_admin: true

sensor:
  - platform: sql
    db_url: !secret peripheral_url
    queries:
      - name: Rain Last Hour
        query: "select sum(amount_since_last_read) as rainfall from rain_sensor where read_at > (select now() - interval '1' hour);"
        column: "rainfall"
        unit_of_measurement: mm
      - name: Rain Last Day
        query: "select sum(amount_since_last_read) as rainfall from rain_sensor where read_at > (select now() - interval '24' hour);"
        column: "rainfall"
        unit_of_measurement: mm
      - name: Rain Last Week
        query: "select sum(amount_since_last_read) as rainfall from rain_sensor where read_at > (select now() - interval '168' hour);"
        column: "rainfall"
        unit_of_measurement: mm
  - platform: aqualogic
    monitored_conditions:
      - pool_temp
      - spa_temp
      - status
  - platform: darksky
    api_key: !secret darksky_api_key
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
    hourly_forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
    scan_interval:
      minutes: 5

switch:
  - platform: aqualogic
    monitored_conditions:
      - filter
      - lights
      - aux_1

cover:
  - platform: mqtt
    name: "Garage Door"
    command_topic: "garadget/Garage/command"
    state_topic: "garadget/Garage/status"
    payload_open: "open"
    payload_close: "close"
    state_open: "open"
    state_closed: "closed"
    value_template: '{{ value_json.status }}'

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

telegram_bot:
  platform: polling
  api_key: !secret telegram_key
  allowed_chat_ids:
    - !secret telegram_chat_id

notify:
 - name: halladay_bot
   platform: telegram
   chat_id: !secret telegram_chat_id

amcrest:
  - host: 192.168.68.53
    name: Garage
    username: admin
    password: !secret armcrest_password
    resolution: high
    stream_source: rtsp
    binary_sensors:
      - motion_detected
  - host: 192.168.68.64
    name: Playroom
    username: admin
    password: !secret armcrest_password
    resolution: high
    stream_source: rtsp
    binary_sensors:
      - motion_detected

recorder:
  db_url: !secret db_url
  exclude:
    domains:
      - automation
      - updater
      - input_boolean
      - input_number
      - input_select
      - input_datetime
      - input_string
      - script
    entities:
      - group.machine_info
      - sun.sun
      - sensor.date
  include:
    domains:
      - binary_sensor
      - cover
      - device_tracker
      - light
      - sensor
      - switch
      - media_player
      - person
device_tracker:
  - platform: iphonedetect
    consider_home: 60
    new_device_defaults:
      track_new_devices: true
    hosts:
      david_iphone: 192.168.68.50
      sarah_iphone: 192.168.68.60
      amanda_iphone: 192.168.68.76
      noah_iphone: 192.168.68.77
      brianna_iphone: 192.168.68.79

group:
  family:
    name: Family
    entities:
      - person.david
      - person.sarah
      - person.amanda
      - person.noah
      - person.brianna
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
      - room_numbers
automation: !include automations.yaml
