homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 37
  unit_system: imperial
  time_zone: America/New_York
  auth_providers:
    - type: homeassistant

frontend:
http:
  ip_ban_enabled: True
  login_attempts_threshold: 10
discovery:
conversation:
history:
logbook:
map:
sun:
config:

mqtt:
  broker: mqtt
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

panel_iframe:
  nodered:
    title: NodeRed
    icon: mdi:shuffle-variant
    url: http://skywalker.local:1880
    require_admin: true
  grafana:
    title: Grafana
    icon: mdi:wrench
    url: http://skywalker.local:3000
    require_admin: true

recorder:
  db_url: !secret db_url
  exclude:
    domains:
      - automation
      - updater
      - input_boolean
      - input_number
      - input_select
      - input_datetime
      - input_string
      - script
    entities:
      - group.machine_info
      - sun.sun
      - sensor.date
  include:
    domains:
      - binary_sensor
      - cover
      - device_tracker
      - light
      - sensor
      - switch
      - media_player
