homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 350
  unit_system: us_customary
  time_zone: America/Los_Angeles
  auth_providers:
    - type: homeassistant
  customize: !include customize.yaml
  country: US

frontend:
http:
  # ip_ban_enabled: True
  # login_attempts_threshold: 50
  use_x_forwarded_for: true
  trusted_proxies:
    # - 192.168.68.0/20  # Local Lan
    - 172.18.0.0/16  # Docker net
    - 127.0.0.1
conversation:
history:
logbook:
sun:
config:
system_health:
stream:
default_config:

wemo:

notify:
 - name: halladay_bot
   platform: telegram
   chat_id: !secret telegram_chat_id

recorder:
  db_url: !secret db_url
  exclude:
    domains:
      - automation
      - updater
      - input_boolean
      - input_number
      - input_select
      - input_datetime
      - input_string
      - script
    entities:
      - group.machine_info
      - sun.sun
      - sensor.date
  include:
    domains:
      - binary_sensor
      - cover
      - device_tracker
      - light
      - sensor
      - switch
      - media_player
      - person

group:
  family:
    name: Family
    entities:
      - person.david
      - person.sarah
      - person.noah
      - person.brianna
      - person.elana

automation: !include automations.yaml
